### ISSUE TITLE
Plasma 6 / Qt6 support?

### ISSUE THREAD

**Issue by xfzv** [pwyde/monochrome-kde#6] opened 2024-03-10 18:16 UTC
Just wondering whether Plasma 6 / Qt6 support is planned or not.

I'm only using AwesomeWM + a few Plasma apps so I don't know whether the theme works fine for the whole Plasma desktop in its current state.

I'm seeing a few minor issues with Dolphin 24.02 but for the most part it's still working fine.

Thanks!

**Comment by array-in-a-matrix** [comment] 2024-03-11 22:35
Hi, the theme seems to be working properly on Plasma 6; however, the SDDM theme broke.

**Comment by array-in-a-matrix** [comment] 2024-03-12 17:30
> The splash screen no longer works either (Settings > Color & Themes > Global theme), clicking the preview doesn't do anything and the default Breeze splash screen is used even when Monochrome is selected.

Yup, I also experience this too. The non-default splash screens I have installed are not labeled as well. 
Only issue I see with dolphin and other QT apps is that it they are not blurred anymore, just transparent.
Konsole seems to be the exception as it is blurred just fine like before.
SDDM lockscreen works fine eventhough the theme does not work on the login screen.

Other than the SDDM issue, I think the other issues would be fixed in future Plasma patches?

![image](https://github.com/pwyde/monochrome-kde/assets/78233840/abe27aca-1e56-4b0a-9ead-1bf97affe984)
![image](https://github.com/pwyde/monochrome-kde/assets/78233840/4af6f68e-0f98-420e-83da-97a22702b170)

**Comment by pwyde** [comment] 2024-03-14 08:51
Apologies for the late reply and thank you for the submitted issue with included screenshots.

The short answer is yes. I am planning to make it Plasma/Qt 6 compatible. It is still very new and I have not had much time for testing Plasma 6 myself.

From what I can gather there has been a lot of changes in Plasma that impacts SVG-based themes (Kvantum theme engine). Not to mention many new bugs within Plasma 6 itself. It is therefore a challenge at the moment to know the exact root cause of the problems. Is it in Plasma, Kvantum or the theme?

My plan is to wait a couple of point releases of Plasma. I will also monitor issues for Plasma/Qt 6 related bugs in [Kvantum](https://github.com/tsujan/Kvantum/issues) and wait on them to be submitted/resolved.

Also... Due to an upcoming surgery I will have limited time to make the theme Plasma 6 compatible. I can therefore not give you any ETA when it will be worked on, sorry. All I can say is that it will be worked on at some point.

Until then my suggestion is to switch to Breeze instead of Kvantum as the application style in system settings. I find this setting to be the most compatible and bug free way of using the Monochrome theme at the moment.

**Comment by array-in-a-matrix** [comment] 2024-03-14 18:44
@pwyde Thank you, hope your surgery goes well.

**Comment by array-in-a-matrix** [comment] 2024-03-18 19:15
I have updated Plasma and it looks like it fixed the blur issue.
![image](https://github.com/pwyde/monochrome-kde/assets/78233840/dfd0207e-fcd4-448f-83ee-c151ba9c8f8a)

**Comment by xfzv** [comment] 2024-03-18 21:09
I also noticed the "Space Information" in Dolphin (24.02) looks squashed:
![image](https://github.com/pwyde/monochrome-kde/assets/78810647/77da6da6-52c5-4a5f-8a02-f0889113771d)

**Comment by pwyde** [comment] 2024-04-03 22:30
Theme has been updated and works with Plasma 6.

See latest [release](https://github.com/pwyde/monochrome-kde/releases/tag/20240403) or download directly from System Settings and/or [KDE Store](https://store.kde.org/p/2143824).

**Closed as completed by pwyde** 2024-04-03 22:30 UTC
Labels: bug, enhancement
