### ISSUE TITLE
Right click on the title bar on external monitor opens the dropdown menu on the internal display

### ISSUE THREAD

**Issue by checkinindza** [pwyde/monochrome-kde#8] opened 2024-04-11 22:22 UTC
So, I have a laptop with NVIDIA GPU + AMD iGPU setup if that relevant and an external monitor connected. Overall, I like the theme a lot, so I would just like to say thank you for your work! 

But there's one issue I noticed. If I use right click on the window title bar, for some reason the drop down menu opens in another display whatsoever. I tested this with default Breeze theme and it doesn't have this issue.

But this seems to only happen if I use right click on the external monitor, if I use it on the internal display, it works fine.

**Comment by pwyde** [comment] 2024-04-12 06:12
I only have a single monitor setup unfortunately. I have therefore not seen this issue myself and unable to test properly.

Do you have any other themes installed that uses custom window decorations? For example [Infinity-Color-Aurorae](https://store.kde.org/p/1972103) or any other theme that uses Aurorae?

I suspect that the issue is related to KWin/Aurorae and not specific to Monochrome theme. But rather affects all Aurorae-based window decoration themes.

**Comment by checkinindza** [comment] 2024-04-18 22:10
> I only have a single monitor setup unfortunately. I have therefore not seen this issue myself and unable to test properly.
> 
> Do you have any other themes installed that uses custom window decorations? For example [Infinity-Color-Aurorae](https://store.kde.org/p/1972103) or any other theme that uses Aurorae?
> 
> I suspect that the issue is related to KWin/Aurorae and not specific to Monochrome theme. But rather affects all Aurorae-based window decoration themes.

You are right, it seems to be an issue with KWin/Aurorae, I guess I'll try to report it to KDE and will see what they say.

EDIT:

Didn't have to report it myself, found a few posts on KDE sites already. KDE Developer mentions that it might be a Qt issue (https://discuss.kde.org/t/context-menus-on-right-click-not-working-properly-with-custom-aurorae-themes/13395 and https://bugs.kde.org/show_bug.cgi?id=480864)

**Comment by pwyde** [comment] 2024-04-19 14:57
Closing issue because not caused by theme.

**Closed as completed by pwyde** 2024-04-19 14:57 UTC
